### PR TITLE
Update aiosseclient.py

### PR DESCRIPTION
**Pull request by dwatrous**
Make it possible to provide timeout and add error handling to ensure session is closed. Backward compatible changes.

This does overload the idea of an SSE response because I yield some "events" that were not server sent.

### CODE REVIEW

**Comment by ebraminio** [comment]
Thanks for creating this, apparently 'timeout_total' isn't defined in your PR, guess it should be float, not sure what should be the default value.

This PR shows I should add a test and CI, and python types also later.

**Comment by dwatrous** [comment]
Good catch. I forgot to carry that change over.

**Comment by ebraminio** [comment]
Merged your changes and adopted the project with python typings with some minor API changes, please have a look to see if we proceed and make a release. Thanks!

**Comment by ebraminio** [comment]
> This does overload the idea of an SSE response because I yield some "events" that were not server sent.

I think we should use logging facility of python, what would you think?

**Comment by ebraminio** [comment]
Also adopted the project with flake8 and pylint and added test and lint CI bots, hopefully would look good

**Comment by dwatrous** [comment]
I agree about logging instead of yielding events. I'll work on that soon.

**Comment by dwatrous** [comment]
I think the code looks good. Once you release, I'll test the new release.

**Comment by ebraminio** [comment]
I used logging facilities and made a release, please take a look, thanks! 😊

**Comment by dwatrous** [comment]
The changes look good. My initial test seems to work. I see that you changed the try/except to explicitly catch a TimeoutError. Is that the only error that could be raised? If any other Exception is thrown there, the session won't be closed and the code might hang.

**Comment by ebraminio** [comment]
> I see that you changed the try/except to explicitly catch a TimeoutError. Is that the only error that could be raised?

Oh it was because of 

`aiosseclient.py:143:15: W0718: Catching too general exception Exception (broad-exception-caught)`

Can this look good to you:

```diff
@@ -142,4 +142,6 @@ async def aiosseclient(
                     lines.append(line)
         except TimeoutError as sseerr:
             logging.error('TimeoutError: %s', sseerr)
-            await session.close()
+        finally:
+            if not session.closed:
+                await session.close()
```

**Comment by ebraminio** [comment]
Also thanks to your works I just learnt about https://github.com/rtfol/aiohttp-sse-client and https://github.com/JelleZijlstra/aiohttp-sse-client2 which is inspired from this library, maybe we can adopt parts of them which we need, their handling of status messages also look nice.

**Comment by dwatrous** [comment]
A finally might be a good way to accomplish this. I'm going to test it for a while and see if I get stuck with something other than a TimeourError. So far I think that's the only one I've seen.

**Comment by ebraminio** [comment]
So just applied that.  But it doesn't handle session close when break is put on the client's for loop which apparently needs an API breakage in order to happen sadly but the alternative libraries can do that using a different which we can evolve to become more like them also. Anyway just made a release for this. Thanks 😊

**Pull request merged**
